version: '3.8'

services:
  user-notifications-manager:
    build:
      context: . # Предполагаем, что Dockerfile в корне
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NOTIFICATION_SERVICE_HOST=http://notification-service:5001
      - MAX_RETRIES=5
      - RETRY_INTERVAL=2000
      - AUTH_TOKEN=Bearer onlyvim2024
    depends_on:
      - notification-service

  notification-service:
    image: aryekog/backend-interview-notifications-service:0.0.2
    ports:
      - "5001:5001"
    environment:
      - EMAIL_RATE_LIMIT=1
      - SMS_RATE_LIMIT=1
      - RATE_LIMIT_WINDOW_MS=1000
      - ERROR_RATE=0.1